export const sensorDefinitions = {
  windspeed: {
    title: "Windgeschwindigkeit",
    unit: "m/s",
    sensorType: "WINDSPEED",
    icon: "osem-particulate-matter",
  },
  dht22_temperature: {
    title: "Temperatur",
    unit: "°C",
    sensorType: "DHT22",
    icon: "osem-thermometer",
  },
  bme680_temperature: {
    title: "Lufttemperatur",
    unit: "°C",
    sensorType: "BME680",
    icon: "osem-thermometer",
  },
  smt50_soilmoisture: {
    title: "Bodenfeuchte",
    unit: "%",
    sensorType: "SMT50",
    icon: "osem-thermometer",
  },
  sht3x_temperature: {
    title: "Temperatur",
    unit: "°C",
    sensorType: "SHT3X",
    icon: "osem-thermometer",
  },
  pms5003_pm01: {
    title: "PM01",
    unit: "µg/m³",
    sensorType: "PMS 5003",
    icon: "osem-cloud",
  },
  pms5003_pm25: {
    title: "PM2.5",
    unit: "µg/m³",
    sensorType: "PMS 5003",
    icon: "osem-cloud",
  },
  bme280_pressure_pa: {
    title: "Luftdruck",
    unit: "Pa",
    sensorType: "BME280",
    icon: "osem-barometer",
  },
  bme680_humidity: {
    title: "Luftfeuchte",
    unit: "%",
    sensorType: "BME680",
    icon: "osem-humidity",
  },
  bme280_humidity: {
    title: "rel. Luftfeuchte",
    unit: "%",
    sensorType: "BME280",
    icon: "osem-humidity",
  },
  pms5003_pm10: {
    title: "PM10",
    unit: "µg/m³",
    sensorType: "PMS 5003",
    icon: "osem-cloud",
  },
  bme280_temperature: {
    title: "Temperatur",
    unit: "°C",
    sensorType: "BME280",
    icon: "osem-thermometer",
  },
  veml6070_uvintensity: {
    title: "UV-Intensität",
    unit: "μW/cm²",
    sensorType: "VEML6070",
    icon: "osem-brightness",
  },
  sht3x_humidity: {
    title: "rel. Luftfeuchte",
    unit: "%",
    sensorType: "SHT3X",
    icon: "osem-humidity",
  },
  bme680_pressure: {
    title: "atm. Luftdruck",
    unit: "hPa",
    sensorType: "BME680",
    icon: "osem-barometer",
  },
  tsl45315_lightintensity: {
    title: "Beleuchtungsstärke",
    unit: "lx",
    sensorType: "TSL45315",
    icon: "osem-brightness",
  },
  bmp180_temperature: {
    title: "Temperatur",
    unit: "°C",
    sensorType: "BMP180",
    icon: "osem-thermometer",
  },
  sds011_pm25: {
    title: "PM2.5",
    unit: "µg/m³",
    sensorType: "SDS 011",
    icon: "osem-cloud",
  },
  sps30_pm10: {
    title: "PM10",
    unit: "µg/m³",
    sensorType: "SPS30",
    icon: "osem-cloud",
  },
  soundlevelmeter: {
    title: "Lautstärke",
    unit: "dB (A)",
    sensorType: "SOUNDLEVELMETER",
    icon: "osem-thermometer",
  },
  pms7003_pm25: {
    title: "PM2.5",
    unit: "µg/m³",
    sensorType: "PMS 7003",
    icon: "osem-cloud",
  },
  bme680_voc: {
    title: "VOC",
    unit: "kOhm",
    sensorType: "BME680",
    icon: "osem-thermometer",
  },
  dnms_la_min: {
    title: "Schalldruckpegel (Min)",
    unit: "db (A)",
    sensorType: "DNMS",
    icon: "osem-volume-up",
  },
  dht22_humidity: {
    title: "rel. Luftfeuchte",
    unit: "%",
    sensorType: "DHT22",
    icon: "osem-humidity",
  },
  pms7003_pm01: {
    title: "PM01",
    unit: "µg/m³",
    sensorType: "PMS 7003",
    icon: "osem-cloud",
  },
  dps310_temperature: {
    title: "Temperatur",
    unit: "°C",
    sensorType: "DPS310",
    icon: "osem-thermometer",
  },
  pms7003_pm10: {
    title: "PM10",
    unit: "µg/m³",
    sensorType: "PMS 7003",
    icon: "osem-cloud",
  },
  sps30_pm25: {
    title: "PM2.5",
    unit: "µg/m³",
    sensorType: "SPS30",
    icon: "osem-cloud",
  },
  dps310_pressure: {
    title: "Luftdruck",
    unit: "hPa",
    sensorType: "DPS310",
    icon: "osem-barometer",
  },
  index: {
    title: null,
    unit: null,
    sensorType: null,
    icon: null,
  },
  bme280_pressure_hpa: {
    title: "Luftdruck",
    unit: "hPa",
    sensorType: "BME280",
    icon: "osem-barometer",
  },
  bmp180_pressure_pa: {
    title: "Luftdruck",
    unit: "Pa",
    sensorType: "BMP180",
    icon: "osem-humidity",
  },
  sds011_pm10: {
    title: "PM10",
    unit: "µg/m³",
    sensorType: "SDS 011",
    icon: "osem-cloud",
  },
  sps30_pm1: {
    title: "PM1",
    unit: "µg/m³",
    sensorType: "SPS30",
    icon: "osem-cloud",
  },
  pms1003_pm01: {
    title: "PM01",
    unit: "µg/m³",
    sensorType: "PMS 1003",
    icon: "osem-cloud",
  },
  hdc1080_temperature: {
    title: "Temperatur",
    unit: "°C",
    sensorType: "HDC1080",
    icon: "osem-thermometer",
  },
  pms1003_pm25: {
    title: "PM2.5",
    unit: "µg/m³",
    sensorType: "PMS 1003",
    icon: "osem-cloud",
  },
  scd30_co2: {
    title: "CO₂",
    unit: "ppm",
    sensorType: "SCD30",
    icon: "osem-co2",
  },
  hdc1008_temperature: {
    title: "Temperatur",
    unit: "°C",
    sensorType: "HDC1008",
    icon: "osem-thermometer",
  },
  sps30_pm4: {
    title: "PM4",
    unit: "µg/m³",
    sensorType: "SPS30",
    icon: "osem-cloud",
  },
  pms1003_pm10: {
    title: "PM10",
    unit: "µg/m³",
    sensorType: "PMS 1003",
    icon: "osem-cloud",
  },
  pms3003_pm25: {
    title: "PM2.5",
    unit: "µg/m³",
    sensorType: "PMS 3003",
    icon: "osem-cloud",
  },
  bmp180_pressure_hpa: {
    title: "Luftdruck",
    unit: "hPa",
    sensorType: "BMP180",
    icon: "osem-humidity",
  },
  dnms_la_max: {
    title: "Schalldruckpegel (Max)",
    unit: "db (A)",
    sensorType: "DNMS",
    icon: "osem-volume-up",
  },
  hdc1080_humidity: {
    title: "rel. Luftfeuchte",
    unit: "%",
    sensorType: "HDC1080",
    icon: "osem-humidity",
  },
  pms3003_pm01: {
    title: "PM01",
    unit: "µg/m³",
    sensorType: "PMS 3003",
    icon: "osem-cloud",
  },
  dht11_temperature: {
    title: "Temperatur",
    unit: "°C",
    sensorType: "DHT11",
    icon: "osem-thermometer",
  },
  smt50_soiltemperature: {
    title: "Bodentemperatur",
    unit: "°C",
    sensorType: "SMT50",
    icon: "osem-thermometer",
  },
  dht11_humidity: {
    title: "rel. Luftfeuchte",
    unit: "%",
    sensorType: "DHT11",
    icon: "osem-humidity",
  },
  pms3003_pm10: {
    title: "PM10",
    unit: "µg/m³",
    sensorType: "PMS 3003",
    icon: "osem-cloud",
  },
  dnms_la_eq: {
    title: "Schalldruckpegel",
    unit: "db (A)",
    sensorType: "DNMS",
    icon: "osem-volume-up",
  },
  bmp280_pressure: {
    title: "Luftdruck",
    unit: "hPa",
    sensorType: "BMP280",
    icon: "osem-barometer",
  },
  hdc1008_humidity: {
    title: "rel. Luftfeuchte",
    unit: "%",
    sensorType: "HDC1008",
    icon: "osem-humidity",
  },
};
